name=zs_tools
version=1.0.0
author=zishen
maintainer=zishen
sentence=Lightweight task/event/timer framework
paragraph=Cooperative task scheduler and utility library
category=Device Control
architectures=*
